import {
  type CreationOptional,
  DataTypes,
  type HasManyAddAssociationMixin,
  type HasManyGetAssociationsMixin,
  type HasManyRemoveAssociationMixin,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import { District } from './index.ts';

import { sequelize } from '../utils/db.ts';

import { COUNTRY_MAX_LEN, LOCATION_MAX_LEN, REF_POINT_MAX_LEN }
  from '@strength-inventory/schemas';

class City extends Model<InferAttributes<City>, InferCreationAttributes<City>> {
  declare id: CreationOptional<string>;

  declare name: string;

  declare referencePoint: string;

  declare latitude: number;

  declare longitude: number;

  declare country: string;

  declare createdAt: CreationOptional<Date>;

  declare updatedAt: CreationOptional<Date>;

  declare getDistricts: HasManyGetAssociationsMixin<District>;

  declare addDistrict: HasManyAddAssociationMixin<District, string>;

  declare removeDistrict: HasManyRemoveAssociationMixin<District, string>;
}

City.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, LOCATION_MAX_LEN]
    }
  },
  referencePoint: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, REF_POINT_MAX_LEN]
    }
  },
  latitude: {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false,
    validate: {
      max: 90,
      min: -90
    }
  },
  longitude: {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false,
    validate: {
      max: 180,
      min: -180
    }
  },
  country: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, COUNTRY_MAX_LEN]
    }
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  sequelize,
  underscored: true,
  modelName: 'city'
});

export default City;
