import {
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import { sequelize } from '../utils/db.ts';

class District extends Model<
  InferAttributes<District>, InferCreationAttributes<District>> {
  declare id: CreationOptional<string>;

  declare cityId: string;

  declare name: string;

  declare referencePoint: string;

  declare latitude: number;

  declare longitude: number;

  declare createdAt: CreationOptional<Date>;

  declare updatedAt: CreationOptional<Date>;
}

District.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  cityId: {
    type: DataTypes.UUID,
    allowNull: false,
    references: { model: 'cities', key: 'id' }
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false
  },
  referencePoint: {
    type: DataTypes.STRING,
    allowNull: false
  },
  latitude: {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false
  },
  longitude: {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  sequelize,
  underscored: true,
  modelName: 'district'
});

export default District;
