/* eslint-disable @stylistic/lines-between-class-members */
import {
  type BelongsToManyGetAssociationsMixin,
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import {
  type EquipmentCategory,
  type EquipmentMaximumWeightType,
  type EquipmentWeightUnit,
  MAX_WEIGHT
} from '@strength-inventory/schemas';

import { sequelize } from '../utils/db.js';

import { Gym } from './index.ts';

class Equipment extends Model<
  InferAttributes<Equipment>, InferCreationAttributes<Equipment>
> {
  declare id: CreationOptional<string>;
  declare name: string;
  declare category: EquipmentCategory;
  declare subcategory: string;
  declare manufacturer: string;
  declare code: string;
  declare weightUnit: EquipmentWeightUnit | null | undefined;
  declare weight: number | null | undefined;
  declare startingWeight: number | null | undefined;
  declare availableWeights: number[];
  declare maximumWeight: number | null | undefined;
  declare maximumWeightType: EquipmentMaximumWeightType;
  declare outOfProduction: boolean;
  declare url: string | null | undefined;
  declare notes: string;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare getGyms: BelongsToManyGetAssociationsMixin<Gym>;
}

Equipment.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  category: {
    type: DataTypes
      .ENUM(
        'accessoryOrTool',
        'barOrPlate',
        'cardio',
        'freeWeight',
        'handleAttachment',
        'strengthMachine',
        'system'
      ),
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  /* at the db level, subcategory is only enforced as a string
  instead of an enum because the set of accepted subcategories
  is subject to many small changes in the future */
  subcategory: {
    type: DataTypes.STRING,
    allowNull: false,
    defaultValue: 'other',
    validate: {
      notEmpty: true
    }
  },
  manufacturer: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  code: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  weightUnit: {
    type: DataTypes.ENUM('kg', 'lbs')
  },
  weight: {
    type: DataTypes.DECIMAL(5, 2),
    // as per customValidator(), using this field requires weightUnit !== null
    validate: {
      max: MAX_WEIGHT,
      min: 0.01
    }
  },
  startingWeight: {
    type: DataTypes.DECIMAL(5, 2),
    // as per customValidator(), using this field requires weightUnit !== null
    validate: {
      max: MAX_WEIGHT,
      min: 0.01
    }
  },
  availableWeights: {
    type: DataTypes.JSON
    // as per customValidator(), using this field requires weightUnit !== null
  },
  maximumWeight: {
    type: DataTypes.DECIMAL(5, 2),
    // as per customValidator(), using this field requires weightUnit !== null
    validate: {
      max: MAX_WEIGHT,
      min: 0.01
    }
  },
  maximumWeightType: {
    type: DataTypes.ENUM('load', 'weight')
  },
  outOfProduction: {
    type: DataTypes.BOOLEAN
  },
  url: {
    type: DataTypes.STRING,
    validate: {
      isUrl: true
    }
  },
  notes: {
    type: DataTypes.STRING
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  sequelize,
  underscored: true,
  modelName: 'equipment',
  validate: {
    customValidator () {
      const instance = this as unknown as Equipment;

      if (!instance.weightUnit && (
        instance.weight
        || instance.startingWeight
        || instance.availableWeights.length > 0
        || instance.maximumWeight
      )
      ) {
        throw Error(
          'weight unit must be selected if other weight data is used'
        );
      }

      if ((instance.startingWeight && instance.maximumWeight)
        && instance.startingWeight > instance.maximumWeight) {
        throw Error(
          'starting weight cannot be more than maximum weight'
        );
      }

      if ((instance.availableWeights.length > 0 && instance.startingWeight)
        && Math.min(...instance.availableWeights) !== instance.startingWeight) {
        throw Error(
          'smallest available weight must equal starting weight'
        );
      }

      if ((instance.availableWeights.length > 0 && instance.maximumWeight)
        && Math.max(...instance.availableWeights) !== instance.maximumWeight) {
        throw Error(
          'highest available weight must equal maximum weight'
        );
      }
    }
  }
});

export default Equipment;
