/* eslint-disable @stylistic/lines-between-class-members */
import {
  type BelongsToManyAddAssociationMixin,
  type BelongsToManyGetAssociationsMixin,
  type BelongsToManyRemoveAssociationMixin,
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import { adjustUserRole } from '../utils/middleware.ts';

import type {
  Hours,
  HoursExceptions
} from '@strength-inventory/schemas';

import { sequelize } from '../utils/db.js';

import { Equipment, Membership, User } from './index.ts';

import { COUNTRY_MAX_LEN, LOCATION_MAX_LEN, STREET_NO_MAX_LEN }
  from '@strength-inventory/schemas';

/* the fields declared as 'string | null' do not need
CreationOptional<> for functional reasons but to conveniently
satisfy TS in the .post() route in controllers/gyms.ts */
class Gym extends Model<InferAttributes<Gym>, InferCreationAttributes<Gym>> {
  declare id: CreationOptional<string>;
  declare name: string;
  declare chain: CreationOptional<string | null>;
  declare street: string;
  declare streetNumber: string;
  declare district: string;
  declare city: string;
  declare country: string;
  declare latitude: number;
  declare longitude: number;
  declare openingHoursEveryone: CreationOptional<Hours>;
  declare openingHoursMembers: CreationOptional<Hours>;
  declare openingHoursExceptions: CreationOptional<HoursExceptions>;
  declare url: CreationOptional<string | null>;
  declare location: string;
  declare equipmentVisible: CreationOptional<boolean>;
  declare membershipsVisible: CreationOptional<boolean>;
  declare openingHoursVisible: CreationOptional<boolean>;
  declare notes: CreationOptional<string | null>;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare getManagers: BelongsToManyGetAssociationsMixin<User>;
  declare getMemberships: BelongsToManyGetAssociationsMixin<Membership>;
  declare addMembership: BelongsToManyAddAssociationMixin<Membership, string>;
  declare removeMembership:
  BelongsToManyRemoveAssociationMixin<Membership, string>;
  declare getEquipment: BelongsToManyGetAssociationsMixin<Equipment>;
  declare addEquipment: BelongsToManyAddAssociationMixin<Equipment, string>;
  declare removeEquipment:
  BelongsToManyRemoveAssociationMixin<Equipment, string>;
}

Gym.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  chain: {
    type: DataTypes.STRING,
    defaultValue: null,
    validate: {
      notEmpty: true
    }
  },
  street: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, LOCATION_MAX_LEN]
    }
  },
  streetNumber: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, STREET_NO_MAX_LEN]
    }
  },
  district: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, LOCATION_MAX_LEN]
    }
  },
  city: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, LOCATION_MAX_LEN]
    }
  },
  country: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      len: [1, COUNTRY_MAX_LEN]
    }
  },
  latitude: {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false
  },
  longitude: {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false
  },
  openingHoursEveryone: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {
      MO: [null, null],
      TU: [null, null],
      WE: [null, null],
      TH: [null, null],
      FR: [null, null],
      SA: [null, null],
      SU: [null, null]
    }
  },
  openingHoursMembers: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {
      MO: [null, null],
      TU: [null, null],
      WE: [null, null],
      TH: [null, null],
      FR: [null, null],
      SA: [null, null],
      SU: [null, null]
    }
  },
  openingHoursExceptions: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: { data: [] }
  },
  url: {
    type: DataTypes.STRING,
    defaultValue: null,
    validate: {
      isUrl: true
    }
  },
  location: {
    type: DataTypes.STRING(510),
    allowNull: false,
    validate: {
      isUrl: true
    }
  },
  equipmentVisible: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false
  },
  membershipsVisible: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false
  },
  openingHoursVisible: {
    type: DataTypes.BOOLEAN,
    allowNull: false,
    defaultValue: false
  },
  notes: {
    type: DataTypes.STRING,
    defaultValue: null,
    validate: {
      notEmpty: true
    }
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  hooks: {
    beforeDestroy: async (gym) => {  // Turn gym-less managers into gym-goers.
      const managers = await gym.getManagers();
      for (const manager of managers) {
        await adjustUserRole(
          manager.id,
          1  // emptyLength = 1 because this is run before .destroy()
        );
      }
    }
  },
  sequelize,
  underscored: true,
  modelName: 'gym'
});

export default Gym;
