/* eslint-disable @stylistic/lines-between-class-members */
import {
  type BelongsToManyGetAssociationsMixin,
  type CreationOptional,
  DataTypes,
  type InferAttributes,
  type InferCreationAttributes,
  Model
} from 'sequelize';

import {
  COUNTRY_MAX_LEN,
  type MembershipAvailability,
  type MembershipTimeUnit
} from '@strength-inventory/schemas';

import { sequelize } from '../utils/db.js';

import { Gym } from './index.ts';

class Membership extends Model<
  InferAttributes<Membership>, InferCreationAttributes<Membership>
> {
  declare id: CreationOptional<string>;
  declare chain: string | null;
  declare country: string | null;
  declare name: string;
  declare initiationFee: number | null;
  declare membershipFee: number;
  declare feeCurrency: string;
  declare visits: number | null;
  declare validity: number;
  declare validityUnit: MembershipTimeUnit;
  declare commitment: number | null;
  declare commitmentUnit: MembershipTimeUnit | null;
  declare autoRenewal: boolean;
  declare availability: CreationOptional<MembershipAvailability>;
  declare url: string | null;
  declare notes: string | null;
  declare createdAt: CreationOptional<Date>;
  declare updatedAt: CreationOptional<Date>;

  declare getGyms: BelongsToManyGetAssociationsMixin<Gym>;
}

Membership.init({
  id: {
    type: DataTypes.UUID,  // CHAR(36) for MySQL
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
  },
  chain: {
    type: DataTypes.STRING,
    defaultValue: null,
    validate: {
      notEmpty: true
    }
  },
  country: {
    type: DataTypes.STRING,
    validate: {
      len: [1, COUNTRY_MAX_LEN]
    }
  },
  name: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  initiationFee: {
    type: DataTypes.DECIMAL(10, 2)
  },
  membershipFee: {
    type: DataTypes.DECIMAL(10, 2),
    allowNull: false
  },
  feeCurrency: {
    type: DataTypes.STRING,
    allowNull: false,
    validate: {
      notEmpty: true
    }
  },
  visits: {
    type: DataTypes.INTEGER
  },
  validity: {
    type: DataTypes.INTEGER,
    allowNull: false
  },
  validityUnit: {
    type: DataTypes.ENUM('year', 'month', 'week', 'day', 'hour'),
    allowNull: false
  },
  commitment: {
    type: DataTypes.INTEGER
  },
  commitmentUnit: {
    type: DataTypes.ENUM('year', 'month', 'week', 'day', 'hour')
    // As per customValidator(), this field is required if commitment !== null.
  },
  autoRenewal: {
    type: DataTypes.BOOLEAN,
    allowNull: false
  },
  availability: {
    type: DataTypes.JSON,
    allowNull: false,
    defaultValue: {
      Desk: false,
      Web: false,
      App: false,
      Other: false
    }
  },
  url: {
    type: DataTypes.STRING,
    validate: {
      isUrl: true
    }
  },
  notes: {
    type: DataTypes.STRING,
    validate: {
      notEmpty: true
    }
  },
  createdAt: DataTypes.DATE,
  updatedAt: DataTypes.DATE
}, {
  sequelize,
  underscored: true,
  modelName: 'membership',
  validate: {
    customValidator () {
      const instance = this as unknown as Membership;

      if ((instance.chain && !instance.country)
        || (instance.country && !instance.chain)
      ) {
        throw Error(
          'chain and country must both be given or left empty'
        );
      }

      if (!instance.commitmentUnit && instance.commitment) {
        throw Error(
          'commitment unit must be selected if there is commitment'
        );
      }
    }
  }
});

export default Membership;
