import { DataTypes } from 'sequelize';
import { type Migration } from '../utils/db.ts';
// .ts instead of .js to accommodate Vitest

const up: Migration = async ({ context: queryInterface }) => {
  await queryInterface.addColumn('gyms', 'latitude', {
    type: DataTypes.DECIMAL(8, 5)
  });

  await queryInterface.sequelize.query(
    // eslint-disable-next-line @stylistic/quotes
    "UPDATE gyms SET latitude = '0.00001'"
  );

  await queryInterface.changeColumn('gyms', 'latitude', {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false
  });

  await queryInterface.addColumn('gyms', 'longitude', {
    type: DataTypes.DECIMAL(8, 5)
  });

  await queryInterface.sequelize.query(
    // eslint-disable-next-line @stylistic/quotes
    "UPDATE gyms SET longitude = '0.00001'"
  );

  await queryInterface.changeColumn('gyms', 'longitude', {
    type: DataTypes.DECIMAL(8, 5),
    allowNull: false
  });

  await queryInterface.createTable('cities', {
    id: {
      type: DataTypes.UUID,  // CHAR(36) for MySQL
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    reference_point: {
      type: DataTypes.STRING,
      allowNull: false
    },
    latitude: {
      type: DataTypes.DECIMAL(8, 5),
      allowNull: false
    },
    longitude: {
      type: DataTypes.DECIMAL(8, 5),
      allowNull: false
    },
    country: {
      type: DataTypes.STRING,
      allowNull: false
    },
    created_at: DataTypes.DATE,
    updated_at: DataTypes.DATE
  });

  await queryInterface.createTable('districts', {
    id: {
      type: DataTypes.UUID,  // CHAR(36) for MySQL
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4  // Automatically generated by Sequelize.
    },
    city_id: {
      type: DataTypes.UUID,
      allowNull: false,
      references: { model: 'cities', key: 'id' }
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    reference_point: {
      type: DataTypes.STRING,
      allowNull: false
    },
    latitude: {
      type: DataTypes.DECIMAL(8, 5),
      allowNull: false
    },
    longitude: {
      type: DataTypes.DECIMAL(8, 5),
      allowNull: false
    },
    created_at: DataTypes.DATE,
    updated_at: DataTypes.DATE
  });
};

const down: Migration = async ({ context: queryInterface }) => {
  await queryInterface.removeColumn('gyms', 'latitude');
  await queryInterface.removeColumn('gyms', 'longitude');
  await queryInterface.dropTable('districts');
  await queryInterface.dropTable('cities');
};

export { up, down };
